FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    nginx \
    openssl \
    && apt-get clean

COPY ./conf/nginx.conf /etc/nginx/conf.d

RUN mkdir -p /etc/nginx/ssl &&\
    openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/C=AO/ST=Luanda/L=Luanda/O=42/OU=Inception/CN=gbravo-f.42.fr"

ENTRYPOINT ["nginx", "-g", "daemon off;"]